### ISSUE TITLE
Error when run run_all_pipeline.py

### ISSUE THREAD

**Issue by KervinBill** [imatge-upc/activitynet-2016-cvprw#5]
Using Theano backend.
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 8, in <module>
    from src.data import import_labels
ImportError: No module named src.data

**Comment by albertomontesg** [comment]
To solve this it requires to add the src folder into `PYTHONPATH`:
`export PYTHONPATH='$PYTHONPATH:/path/to/src'`

**Comment by KervinBill** [comment]
Thanks， I've  solved. But when I try again, I got this:
Using Theano backend.
Reading Video...
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 188, in <module>
    args.activity_threshold
  File "scripts/run_all_pipeline.py", line 22, in run_all_pipeline
    video_array = video_to_array(input_video, resize=input_size)
  File "/path/toactivitynet-2016-cvprw-master/venv/local/lib/python2.7/site-packages/src/io.py", line 38, in video_to_array
    raise Exception('Could not open the video')
Exception: Could not open the video

Does it mean I have  opencv install inside the virtual environment ?  my machine has OPENCV. Thank u very much.

**Comment by albertomontesg** [comment]
This means that OpenCV is not able to open the file. The usual setup is to create a virtual environment with `--system-site-packages` so if you have OpenCV installed on your system, it will be accessible on the virtual environment.

If you have already done this, take a look to the video where this exception is happening and maybe it can be due to incompatibility or file being damaged.

**Comment by dudtroc** [comment]
(theano3) ailab@ailab-All-Series:~/HAR/activitynet-2016-cvprw-master$ python scripts/run_all_pipeline.py -i data/activitynet/GCtrfXIBbwA.mp4
Using Theano backend.
Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled, cuDNN 5005)
Reading Video...
3.2.0                                                                   # print(cv2.__version__)
data/activitynet/GCtrfXIBbwA.mp4                    # print(video_path)
Unable to stop the stream: Inappropriate ioctl for device
<VideoCapture 0x7fc870457f90>
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 192, in <module>
    args.activity_threshold
  File "scripts/run_all_pipeline.py", line 26, in run_all_pipeline
    video_array = video_to_array(input_video, resize=input_size)
  File "./src/io.py", line 42, in video_to_array
    raise Exception('Could not open the video')
Exception: Could not open the video

I also tried about it but it's not still working 
I'm using the actvitynet dataset and installed opencv by the conda instruction

**Comment by thomhert** [comment]
Hi,
When running run_all_pipeline.py,  i got these errors:
```
Classification:
0.9505	Dodgeball
0.0040	Rope skipping
0.0024	Breakdancing
0.0013	Futsal
0.0011	Belly dance
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 188, in <module>
    args.activity_threshold
  File "scripts/run_all_pipeline.py", line 73, in run_all_pipeline
    activity_threshold
  File "/.../.../data/theano/activitynet-2016-cvprw-master/src/processing.py", line 52, in activity_localization
    scores.append(np.mean(sequence_class_prob[s:e,activity_idx]))
TypeError: slice indices must be integers or None or have an __index__ method
```
Something wrong for activity localization, do you know why? Thanks

**Comment by dudtroc** [comment]
I don't know exactly what is something wrong

I guess that keras version is different or uninstalled numpy

this is my result on my computer
[image: 본문 이미지 1]
I execute this program on keras102 version

so if you want to install keras102 version  run this instruction

pip install git+git://github.com/fchollet/keras.git@1.0.2


2017-02-24 19:09 GMT+09:00 thomhert <notifications@github.com>:

**Comment by yclai1114** [comment]
Classification:
0.7912	Cleaning sink
0.0615	Knitting
0.0291	Washing dishes
0.0160	Washing hands
0.0120	Peeling potatoes
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 188, in <module>
    args.activity_threshold
  File "scripts/run_all_pipeline.py", line 73, in run_all_pipeline
    activity_threshold
  File "/home/ubuntu/Desktop/yc/activitynet-2016-cvprw-master/scripts/src/processing.py", line 52, in activity_localization
    scores.append(np.mean(sequence_class_prob[s:e,activity_idx]))
TypeError: slice indices must be integers or None or have an __index__ method

Same problem after run run_all_pipeline.py. Any solution please?

**Comment by albertomontesg** [comment]
Which version of Numpy are you using? I have checked and with version 1.11.2 should work. If not try to print the values of `s`, `e` and `activity_idx` to console and put here the output please.

**Comment by Amysiat** [comment]
@albertomontesg  hello, I have a question to ask you. I want to use your model to train my own dataset, so i need to get the dataset/video.json . what should i do to get the video.json or dataset? I am  looking forward your reply,thank you!

**Comment by kousik97** [comment]
I get the following error while trying to execute run_all_pipeline.py:

Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 4, in <module>
    from keras.layers import (LSTM, BatchNormalization, Convolution3D, Dense, Dropout, Flatten, Input,
  File "/home2/koushik/venv/local/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import backend
  File "/home2/koushik/venv/local/lib/python2.7/site-packages/keras/backend/__init__.py", line 54, in <module>
    from .tensorflow_backend import *
  File "/home2/koushik/venv/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 75, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/home2/koushik/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 22, in <module>
    import zipfile
  File "/usr/lib/python2.7/zipfile.py", line 501, in <module>
    class ZipExtFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'

**Comment by kousik97** [comment]
I have solved the previous error, but now I am getting a new error:
Please help me.
Using TensorFlow backend.
Reading Video...
Duration: 130.6s
FPS: 30.0
Number of frames: 3919
Loading C3D network...
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 188, in <module>
    args.activity_threshold
  File "scripts/run_all_pipeline.py", line 40, in run_all_pipeline
    model  = C3D_conv_features(True)
  File "scripts/run_all_pipeline.py", line 99, in C3D_conv_features
    trainable=False))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 448, in __init__
    ' is currently only working with Theano backend.')
Exception: Convolution3D is currently only working with Theano backend.

**Comment by Amysiat** [comment]
I think you should Change your backend,the default backend is tensorflow.


------------------ 原始邮件 ------------------
发件人: "kousik97";<notifications@github.com>;
发送时间: 2017年5月31日(星期三) 下午2:08
收件人: "imatge-upc/activitynet-2016-cvprw"<activitynet-2016-cvprw@noreply.github.com>; 
抄送: "0℃的温度"<1358584332@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [imatge-upc/activitynet-2016-cvprw] Error when runrun_all_pipeline.py (#5)




I have solved the previous error, but now I am getting a new error:
 Please help me.
 Using TensorFlow backend.
 Reading Video...
 Duration: 130.6s
 FPS: 30.0
 Number of frames: 3919
 Loading C3D network...
 Traceback (most recent call last):
 File "scripts/run_all_pipeline.py", line 188, in 
 args.activity_threshold
 File "scripts/run_all_pipeline.py", line 40, in run_all_pipeline
 model  = C3D_conv_features(True)
 File "scripts/run_all_pipeline.py", line 99, in C3D_conv_features
 trainable=False))
 File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 448, in init
 ' is currently only working with Theano backend.')
 Exception: Convolution3D is currently only working with Theano backend.

**Comment by kousik97** [comment]
Thank you so much. 
I have changed that and it is working but I am getting the following error now:
I am trying to run it on a CPU.
Please help.



Using Theano backend.
Reading Video...
Duration: 130.6s
FPS: 30.0
Number of frames: 3919
Loading C3D network...
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 188, in <module>
    args.activity_threshold
  File "scripts/run_all_pipeline.py", line 40, in run_all_pipeline
    model  = C3D_conv_features(True)
  File "scripts/run_all_pipeline.py", line 99, in C3D_conv_features
    trainable=False))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 114, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 341, in create_input_layer
    self(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 552, in call
    filter_shape=self.W_shape)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 919, in conv3d
    conv_out = dnn.dnn_conv3d(x, kernel, border_mode=border_mode)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 1257, in dnn_conv3d
    return GpuDnnConv3d(algo=algo)(img, kerns, out, desc)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 513, in __init__
    super(GpuDnnConv3d, self).__init__(inplace=inplace, algo=algo)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 328, in __init__
    if version() < (3000, 3000):
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py", line 407, in dnn_version
    dnn_available.msg)
Exception: ("We can't determine the cudnn version as it is not available", 'CUDA not available')

**Comment by amit309b** [comment]
I am getting error can anyone please solve this :
Using Theano backend.
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 4, in <module>
    from keras.layers import (LSTM, BatchNormalization, Convolution3D, Dense, Dropout, Flatten, Input,
  File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 3, in <module>
    from . import activations
  File "/usr/local/lib/python2.7/dist-packages/keras/activations.py", line 4, in <module>
    from . import backend as K
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 70, in <module>
    from .theano_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 3, in <module>
    import theano
  File "/home/inkers/.local/lib/python2.7/site-packages/theano/__init__.py", line 70, in <module>
    from theano.compile import (
  File "/home/inkers/.local/lib/python2.7/site-packages/theano/compile/__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "/home/inkers/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 21, in <module>
    import theano.compile.mode
  File "/home/inkers/.local/lib/python2.7/site-packages/theano/compile/mode.py", line 10, in <module>
    import theano.gof.vm
  File "/home/inkers/.local/lib/python2.7/site-packages/theano/gof/vm.py", line 659, in <module>
    from . import lazylinker_c
  File "/home/inkers/.local/lib/python2.7/site-packages/theano/gof/lazylinker_c.py", line 125, in <module>
    args = cmodule.GCC_compiler.compile_args()
  File "/home/inkers/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2088, in compile_args
    default_compilation_result, default_execution_result = try_march_flag(GCC_compiler.march_flags)
  File "/home/inkers/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1856, in try_march_flag
    flags=cflags, try_run=True)
  File "/home/inkers/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2188, in try_compile_tmp
    comp_args)
  File "/home/inkers/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1756, in _try_compile_tmp
    fd, path = tempfile.mkstemp(suffix='.c', prefix=tmp_prefix)
  File "/usr/lib/python2.7/tempfile.py", line 307, in mkstemp
    dir = gettempdir()
  File "/usr/lib/python2.7/tempfile.py", line 275, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python2.7/tempfile.py", line 200, in _get_default_tempdir
    with _io.open(fd, 'wb', closefd=False) as fp:
AttributeError: 'module' object has no attribute 'open'

**Comment by amit309b** [comment]
hey @kousik97  how did u solve this error
File "/usr/lib/python2.7/zipfile.py", line 501, in
class ZipExtFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'

**Comment by kousik97** [comment]
Yeah, I solved it. The problem is the io.py in src directory. Rename the io.py to io1.py and correspondingly change the places in which io is used. That worked for me. 
The problem is zipfile is executing the io package in the python library and not the local io.py in our directory.

Meanwhile, are you using GPU to run the demo?

**Comment by mdasifjalal** [comment]
I am getting this error, please help or suggest something
Using Theano backend.
Reading Video...
Duration: 22.2s
FPS: 25.0
Number of frames: 555
Loading C3D network...
scripts/run_all_pipeline.py:106: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(64, (3, 3, 3), name="conv1", activation="relu", trainable=False, input_shape=(3, 16, 11..., padding="same", strides=(1, 1, 1))`
  trainable=False))
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 284, in <module>
    args.activity_threshold)
  File "scripts/run_all_pipeline.py", line 40, in run_all_pipeline
    model = C3D_conv_features(True)
  File "scripts/run_all_pipeline.py", line 106, in C3D_conv_features
    trainable=False))
  File "/home/asif/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/models.py", line 443, in add
    layer(x)
  File "/home/asif/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/asif/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 172, in call
    dilation_rate=self.dilation_rate)
  File "/home/asif/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 1944, in conv3d
    conv_out = T.nnet.conv3d(x, kernel,
AttributeError: 'module' object has no attribute 'conv3d'

**Comment by amit309b** [comment]
@mdasifjalal 
it seems that you written code in tensorflow as shown T and used theano as backened.
conv_out = T.nnet.conv3d(x, kernel,

**Comment by mdasifjalal** [comment]
nope, that is not the problem. I think, it was a version mismatch .

**Comment by kartikeyaSh** [comment]
Duration: 6.6s
FPS: 25.0
Number of frames: 164
Loading C3D network...
Extracting features...
10/10 [==============================] - 4s     
Loading temporal localization network...
____________________________________________________________________________________________________
Layer (type)                       Output Shape        Param #     Connected to                     
====================================================================================================
features (InputLayer)              (1, 1, 4096)        0                                            
____________________________________________________________________________________________________
normalization (BatchNormalization) (1, 1, 4096)        8192        features[0][0]                   
____________________________________________________________________________________________________
dropout_1 (Dropout)                (1, 1, 4096)        0           normalization[0][0]              
____________________________________________________________________________________________________
lsmt1 (LSTM)                       (1, 1, 512)         9439232     dropout_1[0][0]                  
____________________________________________________________________________________________________
dropout_2 (Dropout)                (1, 1, 512)         0           lsmt1[0][0]                      
____________________________________________________________________________________________________
fc (TimeDistributed)               (1, 1, 201)         103113      dropout_2[0][0]                  
====================================================================================================
Total params: 9550537
____________________________________________________________________________________________________
Predicting...
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 287, in <module>
    args.activity_threshold)
  File "scripts/run_all_pipeline.py", line 58, in run_all_pipeline
    Y = Y.reshape(nb_clips, 1, 4096)
ValueError: cannot reshape array of size 32112640 into shape (10,1,4096)

any guesses why i get this error and how can i correct it?

**Comment by wasim-ee37** [comment]
Predicting...
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 291, in <module>
    args.activity_threshold)
  File "scripts/run_all_pipeline.py", line 64, in run_all_pipeline
    Y = Y.reshape(nb_clips, 1, 4096)
ValueError: cannot reshape array of size 9253 into shape (19,1,4096)

Why am I encountering this error? Please somebody help me out in this.

**Comment by EMCL** [comment]
hi,
i am getting below error when running 
`python scripts/run_all_pipeline.py -i test2.avi`


```
Exception: ('The following error happened while compiling the node', GpuDnnConv3d{algo='small', inplace=False}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty.0, GpuDnnConvDesc{border_mode=(1, 1, 1), subsample=(1, 1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0}), '\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -Xlinker -rpath,/usr/local/cuda-8.0/lib64 -arch=sm_35 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/lanka/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.13-64/cuda_ndarray -I/home/lanka/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.13-64/cuda_ndarray -I/usr/local/cuda-8.0/include -I/home/lanka/anaconda2/envs/activitynet/lib/python2.7/site-packages/theano/sandbox/cuda -I/home/lanka/anaconda2/envs/activitynet/lib/python2.7/site-packages/numpy/core/include -I/home/lanka/anaconda2/envs/activitynet/include/python2.7 -I/home/lanka/anaconda2/envs/activitynet/lib/python2.7/site-packages/theano/gof -o /home/lanka/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.13-64/tmpakYa3E/46fc805ce0bc8d50ab0e937e59958ac5.so mod.cu -L/home/lanka/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.13-64/cuda_ndarray -L/home/lanka/anaconda2/envs/activitynet/lib -lcudart -lcublas -lcuda_ndarray -lcudnn -lpython2.7', "[GpuDnnConv3d{algo='small', inplace=False}(<CudaNdarrayType(float32, 5D)>, <CudaNdarrayType(float32, 5D)>, <CudaNdarrayType(float32, 5D)>, <CDataType{cudnnConvolutionDescriptor_t}>, Constant{1.0}, Constant{0.0})]")

```

**Comment by MuhammadAsadJaved** [comment]
How should i use backend to Theano?  i am using Ubuntu 16.4?

(venv) asad@asad-Z370P-D3:~/activitynet-2016-cvprw$ python scripts/run_all_pipeline.py -i data/vid2.mp4
Using TensorFlow backend.
Reading Video...
Duration: 5.7s
FPS: 19.9
Number of frames: 113
Loading C3D network...
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 284, in <module>
    args.activity_threshold)
  File "scripts/run_all_pipeline.py", line 40, in run_all_pipeline
    model = C3D_conv_features(True)
  File "scripts/run_all_pipeline.py", line 106, in C3D_conv_features
    trainable=False))
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 448, in __init__
    ' is currently only working with Theano backend.')
Exception: Convolution3D is currently only working with Theano backend.

**Comment by MuhammadAsadJaved** [comment]
> I have solved the previous error, but now I am getting a new error:
> Please help me.
> Using TensorFlow backend.
> Reading Video...
> Duration: 130.6s
> FPS: 30.0
> Number of frames: 3919
> Loading C3D network...
> Traceback (most recent call last):
> File "scripts/run_all_pipeline.py", line 188, in 
> args.activity_threshold
> File "scripts/run_all_pipeline.py", line 40, in run_all_pipeline
> model = C3D_conv_features(True)
> File "scripts/run_all_pipeline.py", line 99, in C3D_conv_features
> trainable=False))
> File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 448, in **init**
> ' is currently only working with Theano backend.')
> Exception: Convolution3D is currently only working with Theano backend.

@kousik97  i also have same error. can you tell me please how to change backend to theano? i am using ubuntu .

**Comment by MuhammadAsadJaved** [comment]
> I think you should Change your backend,the default backend is tensorflow.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "kousik97";<notifications@github.com>; 发送时间: 2017年5月31日(星期三) 下午2:08 收件人: "imatge-upc/activitynet-2016-cvprw"<activitynet-2016-cvprw@noreply.github.com>; 抄送: "0℃的温度"<1358584332@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [imatge-upc/activitynet-2016-cvprw] Error when runrun_all_pipeline.py (#5) I have solved the previous error, but now I am getting a new error: Please help me. Using TensorFlow backend. Reading Video... Duration: 130.6s FPS: 30.0 Number of frames: 3919 Loading C3D network... Traceback (most recent call last): File "scripts/run_all_pipeline.py", line 188, in args.activity_threshold File "scripts/run_all_pipeline.py", line 40, in run_all_pipeline model = C3D_conv_features(True) File "scripts/run_all_pipeline.py", line 99, in C3D_conv_features trainable=False)) File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 448, in init ' is currently only working with Theano backend.') Exception: Convolution3D is currently only working with Theano backend. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Hi, Can you tell me how to change backend to theano? I am using Ubuntu.

**Comment by MuhammadAsadJaved** [comment]
I resolved the backend problem but now i am getting this error.  Can anyone guide me please. 

(venv) asad@asad-Z370P-D3:~/activitynet-2016-cvprw$ python scripts/run_all_pipeline.py -i data/vid2.mp4
Using Theano backend.
ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.
Reading Video...
Duration: 5.7s
FPS: 19.9
Number of frames: 113
Loading C3D network...
Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 287, in <module>
    args.activity_threshold)
  File "scripts/run_all_pipeline.py", line 43, in run_all_pipeline
    model = C3D_conv_features(True)
  File "scripts/run_all_pipeline.py", line 109, in C3D_conv_features
    trainable=False))
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/models.py", line 114, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/engine/topology.py", line 341, in create_input_layer
    self(x)
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 552, in call
    filter_shape=self.W_shape)
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 919, in conv3d
    conv_out = dnn.dnn_conv3d(x, kernel, border_mode=border_mode)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py", line 1257, in dnn_conv3d
    return GpuDnnConv3d(algo=algo)(img, kerns, out, desc)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py", line 513, in __init__
    super(GpuDnnConv3d, self).__init__(inplace=inplace, algo=algo)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py", line 328, in __init__
    if version() < (3000, 3000):
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 404, in dnn_version
    if not dnn_available():
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 340, in dnn_available
    dnn_available.msg)
RuntimeError: You enabled cuDNN, but we aren't able to use it: CUDA not available

**Comment by MuhammadAsadJaved** [comment]
Hi, I have resolved other problems but now I am getting this error while running run_all_pipeline.py

(venv) asad@asad-Z370P-D3:~/activitynet-2016-cvprw$ python scripts/run_all_pipeline.py -i data/vid2.mp4
Using Theano backend.
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device gpu failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1

ERROR (theano.gof.opt): SeqOptimizer apply <theano.sandbox.cuda.dnn.NoCuDNNRaise object at 0x7f3576714610>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py", line 2564, in apply
    if not dnn_available():
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 322, in dnn_available
    v = dnn_version()
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 412, in dnn_version
    profile=False)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1587, in cthunk_factory
    key = self.cmodule_key()
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1285, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1364, in cmodule_key_
    numpy.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7f3576519e10>(), '\n', "'module' object has no attribute '_get_ndarray_c_version'")

Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 5, in <module>
    from keras.layers import (LSTM, BatchNormalization, Convolution3D, Dense, Dropout, Flatten, Input,
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import backend
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/backend/__init__.py", line 51, in <module>
    from .theano_backend import *
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 5, in <module>
    import theano
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/__init__.py", line 111, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_driver.py", line 31, in test_nvidia_driver1
    profile=False)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1587, in cthunk_factory
    key = self.cmodule_key()
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1285, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1364, in cmodule_key_
    numpy.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', GpuCAReduce{add}{1}(<CudaNdarrayType(float32, vector)>), '\n', "'module' object has no attribute '_get_ndarray_c_version'")

**Comment by alexshaodong** [comment]
> Using Theano backend.
> Traceback (most recent call last):
> File "scripts/run_all_pipeline.py", line 8, in
> from src.data import import_labels
> ImportError: No module named src.data

Hello! I have the same problem. Can you teach me how to solve it?
